version: "3"

services:
  web:
    container_name: glpi10
    build: .
    restart: always
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./glpi:/var/www/html/glpi
      - ./docker/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./docker/php/php.ini-development:/usr/local/etc/php/php.ini-development
      - ./docker/php/php.ini-production:/usr/local/etc/php/php.ini-production
    networks:
      - glpi
  db:
    image: mysql:5.7
    container_name: glpi_db
    restart: always
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./docker/db/mysql/data:/var/lib/mysql
    networks:
      - glpi

volumes:
  db_data:

networks:
  glpi:
    driver: bridge